services:
  app:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - "${APP_PORT}:8080"
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "./build" ]
    depends_on:
      - postgres-one
      - redis-one
  redis-one:
    image: redis:latest
    ports:
      - "${REDIS_ONE_PORT}:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_ONE_PASSWORD}" ]
  postgres-one:
    image: postgres:latest
    ports:
      - "${POSTGRES_ONE_PORT}:5432"
    volumes:
      - "../../db/postgres_one/migration:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: ${POSTGRES_ONE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ONE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ONE_DATABASE}
