services:
  app:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    ports:
      - "${APP_PORT}:8080"
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "./build" ]
    depends_on:
      - cockroachdb-one
      - redis-one
  redis-one:
    image: redis:latest
    ports:
      - "${REDIS_ONE_PORT}:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_ONE_PASSWORD}" ]
  cockroachdb-one:
    image: cockroachdb:latest
    ports:
      - "${COCKROACHDB_ONE_NODE_PORT}:26357"
    volumes:
      - "../../db/cockroachdb_one/migration:/docker-entrypoint-initdb.d"
    environment:
      COCKROACHDB_USER: ${COCKROACHDB_ONE_USER}
      COCKROACHDB_PASSWORD: ${COCKROACHDB_ONE_PASSWORD}
      COCKROACHDB_DB: ${COCKROACHDB_ONE_DATABASE}
